// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define WM_SHELLNOTIFY  WM_USER+5

#define TIMER_UHR       100
#define TIMER_UHRA      101

#define DLG_MAIN_X      1001
#define DLG_MAIN_Y      1002
#define DLG_MAIN_Z      1003
#define DLG_EDIT        1004
#define DLG_ALARM       1005

#define IDM_MENU        2001

#define IDR_ICO_MAIN    10001
#define IDR_ICO_TRAY    10002
#define IDR_ICO_TRAY2   10003
#define IDR_ICO_TRAY3   10004
#define IDR_ICO_TRAY4   10005

#define IDD_UHRZEIT     4001
#define IDD_RESTZEIT    4002
#define IDD_ENDZEIT     4003
#define IDI_ACLOCK      4004
#define IDD_EDIT        4005
#define IDI_BCLOCK      4006
#define IDD_5MIN        4007
#define IDD_15MIN       4008
#define IDD_30MIN       4009
#define IDD_60MIN       4010

#define IDM_EDIT        6001
#define IDM_MINI        6002
#define IDM_RESTZEIT    6003
#define IDM_EXIT        6004
#define IDM_RESTORE     6005
#define IDM_HIDE        6006
#define IDM_HIDEX       6007
#define IDM_HIDEY       6008
#define IDM_HIDEZ       6009
#define IDM_TOP         6010
#define IDM_TOPX        6011
#define IDM_TOPY        6012
#define IDM_TOPZ        6013

#define IDD_ALARM_TEXT  7001

#define IDD_EDIT_ZEIT   8001
#define IDD_EDIT_GRUND  8002
#define IDD_TEXT_ZEIT   8003
#define IDD_TEXT_GRUND  8004
#define IDD_TEXT_ENDE   8005
